# -*- coding: utf-8 -*
import os
import time
#running = True
os.system('pyresttest http://10.91.4.11 01_new_admin_add_pre_config.yaml')
time.sleep(1)
os.system('python 02_new_attacker_add_report_attack.py')
time.sleep(1)
os.system('python 03_new_victimer_add_report_victim.py')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 04_new_judge_report.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 05_new_admin_check—report-status.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 06_new_admin_create_strategy_1judge.yaml')
time.sleep(1)
os.system('python 07_new_admin_add_report_attack_strategy_1judge.py.py')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 08_new_admin_distribute_report_attack_check-report-status.yaml')
time.sleep(1)
os.system('python 09_new_admin_add_report_victim_strategy_1judge.py')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 10_new_admin_distribute_report_victim_check-report-status.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 11_new_expert_report.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 12_new_admin_check-report-status.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 13_new_admin_delete_strategy1.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 14_new_admin_create_strategy_2judge.yaml')
time.sleep(1)
os.system('python 15_new_attacker_add_3report_attack_strategy_2judge.py')
time.sleep(1)
os.system('python 16_new_victimer_add_3report_victim_strategy_2judge.py')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 17_new_judge1_6reports_attackandvictim.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 18_new_admin_check-report-status.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 19_new_judge2_6reports_attackandvictim.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 20_new_admin_check-report-status.yaml')
time.sleep(1)
os.system('python 21_new_attacker_create_gwgjsq.py')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 22_new_expert_gwgjsq.yaml')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 23_admin_check_gwgjsq-status.yaml')
time.sleep(1)
os.system('python 24_judge_create_wgxwkf-attack-and-victim.py')
time.sleep(1)
os.system('pyresttest http://10.91.4.11 25_admin_check_koufenshengxiao.yaml')